# Generated by Django 5.1.13 on 2025-12-09 19:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_fuelstation_fuellog_fuel_station_ref'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('LEASE', 'Leasing'), ('RENTAL', 'Locação'), ('SERVICE', 'Serviço')], max_length=20)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_cnpj', models.CharField(blank=True, max_length=18)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_model', models.CharField(choices=[('FIXED', 'Valor fixo'), ('PER_KM', 'Por KM rodado'), ('PER_DAY', 'Por dia'), ('MONTHLY_WITH_KM', 'Mensal com franquia de KM')], max_length=30)),
                ('base_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('included_km_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('EXPIRED', 'Vencido')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tenants.municipality')),
            ],
            options={
                'ordering': ['-start_date', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('custom_billing_model', models.CharField(blank=True, choices=[('FIXED', 'Valor fixo'), ('PER_KM', 'Por KM rodado'), ('PER_DAY', 'Por dia'), ('MONTHLY_WITH_KM', 'Mensal com franquia de KM')], max_length=30, null=True)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='contracts.contract')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_vehicles', to='tenants.municipality')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('odometer_start', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('billed_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado'), ('INVOICED', 'Faturado')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_periods', to='contracts.contract')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_periods', to='tenants.municipality')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_periods', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('municipality', 'contract_number'), name='contract_number_unique_per_municipality'),
        ),
    ]
