# Generated by Django 5.1.13 on 2025-12-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('drivers', '0003_driver_free_trip_enabled'),
        ('fleet', '0004_vehicle_current_contract_vehicle_ownership_type'),
        ('forms', '0001_initial'),
        ('tenants', '0001_initial'),
        ('trips', '0008_alter_freetrip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_index=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='tenants.municipality')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('URBAN', 'Urbana'), ('RURAL', 'Rural'), ('SPECIAL', 'Especial'), ('EVENT', 'Evento')], default='URBAN', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('planned_capacity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='contracts.contract')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tenants.municipality')),
                ('preferred_drivers', models.ManyToManyField(blank=True, related_name='preferred_routes', to='drivers.driver')),
                ('preferred_vehicles', models.ManyToManyField(blank=True, related_name='preferred_routes', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='drivers.driver')),
                ('generated_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='trips.trip')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.municipality')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport_planning.route')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Embarque'), ('DROPOFF', 'Desembarque'), ('WAYPOINT', 'Passagem')], default='WAYPOINT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='tenants.municipality')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport_planning.route')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('SCHOOL', 'Escola'), ('HEALTH', 'Saúde'), ('SOCIAL_ASSISTANCE', 'Assistência Social'), ('OTHER', 'Outro')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_units', to='tenants.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_units', to='tenants.municipality')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_units', to='transport_planning.route')),
                ('service_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_units', to='transport_planning.serviceunit')),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('SCHEDULED', 'Recorrente'), ('ON_DEMAND', 'Sob demanda'), ('MIXED', 'Híbrido')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('requires_authorization', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_services', to='forms.formtemplate')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_services', to='tenants.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('NEEDS_CORRECTION', 'Correção Necessária')], default='PENDING', max_length=32)),
                ('status_notes', models.TextField(blank=True)),
                ('correction_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='forms.formsubmission')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='tenants.municipality')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transport_planning.person')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='transport_planning.route')),
                ('transport_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transport_planning.transportservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='transport_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport_planning.transportservice'),
        ),
        migrations.CreateModel(
            name='EligibilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rules_json', models.JSONField(blank=True, default=dict)),
                ('decision_mode', models.CharField(choices=[('AUTO_APPROVE', 'Aprovar automaticamente'), ('AUTO_DENY', 'Negar automaticamente'), ('AUTO_THEN_REVIEW', 'Auto e revisar'), ('MANUAL_REVIEW_ONLY', 'Somente revisão manual')], default='MANUAL_REVIEW_ONLY', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_policies', to='tenants.municipality')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_policies', to='transport_planning.route')),
                ('transport_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_policies', to='transport_planning.transportservice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('municipality', 'cpf'), name='unique_active_person_per_municipality'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('route', 'date', 'vehicle', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceunit',
            unique_together={('municipality', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='routeunit',
            unique_together={('route', 'service_unit')},
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('municipality', 'code'), name='route_code_unique_per_municipality'),
        ),
    ]
