# Generated by Django 5.1.13 on 2025-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('fleet', '0003_fuelstation_fuellog_fuel_station_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_in_use', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'Próprio'), ('LEASED', 'Leasing'), ('RENTED', 'Alugado'), ('THIRD_PARTY', 'Terceiro')], default='OWNED', max_length=20),
        ),
    ]
