# Generated by Django 5.1.13 on 2025-12-17 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_driver_free_trip_enabled'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VACATION', 'Férias'), ('SICK_LEAVE', 'Afastamento/Atestado'), ('DAY_OFF', 'Folga'), ('TRAINING', 'Treinamento'), ('ADMIN_BLOCK', 'Bloqueio administrativo'), ('OTHER', 'Outro')], max_length=32)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='driver_blocks/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='drivers.driver')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_availability_blocks', to='tenants.municipality')),
            ],
            options={
                'ordering': ['-start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='drivers.driver')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_work_schedules', to='tenants.municipality')),
            ],
            options={
                'ordering': ['driver_id', 'weekday', 'start_time'],
                'unique_together': {('driver', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
