# Generated by Django 5.1.13 on 2025-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('trips', '0003_merge_0002_trip_category_and_cargo_fields_0002_trip_passengers_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='trip',
            name='rental_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='contracts.rentalperiod'),
        ),
    ]
