# Generated by Django 5.1.13 on 2025-12-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_freetrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
