# Generated by Django 5.1.13 on 2025-12-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_free_trip_enabled'),
        ('tenants', '0001_initial'),
        ('trips', '0008_alter_freetrip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTripIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_trip_incidents', to='drivers.driver')),
                ('free_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='trips.freetrip')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_trip_incidents', to='tenants.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
