# Generated by Django 5.1.5 on 2026-01-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tripgpsping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tripgpsping',
            new_name='trips_tripg_trip_id_86e071_idx',
            old_name='trips_trip_trip_id_1b7d7f_idx',
        ),
        migrations.RenameIndex(
            model_name='tripgpsping',
            new_name='trips_tripg_driver__b455e8_idx',
            old_name='trips_trip_driver__a1c2d9_idx',
        ),
    ]
