# Generated by Django 5.1.5 on 2026-01-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('drivers', '0004_driver_geofence'),
        ('fleet', '0007_vehicle_image'),
        ('health', '0001_initial'),
        ('students', '0002_classgroup_student_class_group'),
        ('tenants', '0002_municipality_fuel_contract_settings'),
        ('trips', '0011_rename_trips_trip_trip_id_1b7d7f_idx_trips_tripg_trip_id_86e071_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('EDUCATION', 'Educação'), ('HEALTH', 'Saúde'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('recurrence', models.CharField(choices=[('NONE', 'Única'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='NONE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('return_time_expected', models.TimeField()),
                ('planned_capacity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_trips', to='drivers.driver')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='tenants.municipality')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedTripPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('STUDENT', 'Aluno'), ('PATIENT', 'Paciente'), ('COMPANION', 'Acompanhante')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trip_passengers', to='health.companion')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trip_passengers', to='health.patient')),
                ('planned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trips.plannedtrip')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trip_passengers', to='students.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TripExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('EDUCATION', 'Educação'), ('HEALTH', 'Saúde'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_return', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_return', models.DateTimeField(blank=True, null=True)),
                ('planned_capacity', models.PositiveIntegerField(default=0)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_executions', to='drivers.driver')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_executions', to='tenants.municipality')),
                ('planned_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='trips.plannedtrip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_executions', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_departure', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='trips.tripexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripManifestPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('STUDENT', 'Aluno'), ('PATIENT', 'Paciente'), ('COMPANION', 'Acompanhante')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_manifest_entries', to='health.companion')),
                ('linked_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_manifest_links', to='health.patient')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trips.tripmanifest')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_manifest_entries', to='health.patient')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_manifest_entries', to='students.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlannedTripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_trip_stops', to='destinations.destination')),
                ('planned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.plannedtrip')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('planned_trip', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TripExecutionStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_execution_stops', to='destinations.destination')),
                ('trip_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.tripexecution')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('trip_execution', 'order')},
            },
        ),
    ]
