# Generated by Django 5.1.5 on 2026-01-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_plannedtrip_plannedtrippassenger_tripexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtrip',
            name='optimize_route',
            field=models.BooleanField(default=True),
        ),
    ]
