# Generated by Django 5.1.5 on 2026-01-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_municipality_fuel_contract_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SCHOOL', 'Escola'), ('HEALTH_UNIT', 'Unidade de Saúde'), ('EVENT', 'Evento'), ('OTHER', 'Outro')], default='OTHER', max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='tenants.municipality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('municipality', 'name')},
            },
        ),
    ]
