# Generated by Django 5.1.13 on 2025-12-10 19:36

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=forms.models.default_public_id, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('require_cpf', models.BooleanField(default=True)),
                ('form_type', models.CharField(choices=[('STUDENT_CARD_APPLICATION', 'Solicitação de Carteirinha'), ('GENERIC', 'Genérico')], default='STUDENT_CARD_APPLICATION', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='tenants.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=20)),
                ('protocol_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('NEEDS_CORRECTION', 'Correção Necessária')], default='PENDING', max_length=32)),
                ('status_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formtemplate')),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='students.student')),
                ('linked_student_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='students.studentcard')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='tenants.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('field_name', models.SlugField(max_length=100)),
                ('type', models.CharField(choices=[('SHORT_TEXT', 'Resposta Curta'), ('LONG_TEXT', 'Parágrafo'), ('MULTIPLE_CHOICE', 'Múltipla Escolha'), ('CHECKBOXES', 'Caixas de Seleção'), ('DROPDOWN', 'Menu Suspenso'), ('LINEAR_SCALE', 'Escala Linear'), ('MULTIPLE_CHOICE_GRID', 'Grade de Múltipla Escolha'), ('CHECKBOX_GRID', 'Grade de Caixas de Seleção'), ('DATE', 'Data'), ('TIME', 'Hora'), ('FILE_UPLOAD', 'Upload de Arquivo')], max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.formquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=forms.models.form_answer_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formsubmission')),
            ],
            options={
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='formquestion',
            unique_together={('form_template', 'field_name')},
        ),
    ]
