# Generated by Django 5.1.5 on 2026-01-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formanswer_staff_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
