# Generated by Django 5.1.13 on 2025-12-13 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0004_vehicle_current_contract_vehicle_ownership_type'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=16)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_parts', to='tenants.municipality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('municipality', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='tenants.municipality')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.inventorypart')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('KM', 'Quilometragem'), ('TIME', 'Tempo')], max_length=8)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_service_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='tenants.municipality')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('CORRECTIVE', 'Corretiva'), ('PREVENTIVE', 'Preventiva'), ('TIRE', 'Pneus')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('IN_PROGRESS', 'Em andamento'), ('WAITING_PARTS', 'Aguardando peças'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_odometer_open', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_odometer_close', models.PositiveIntegerField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='tenants.municipality')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_opened', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='maintenance.inventorypart')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.serviceorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='maintenance.serviceorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('STOCK', 'Em estoque'), ('IN_USE', 'Em uso'), ('RETREADED', 'Recapado'), ('SCRAPPED', 'Descartado')], default='STOCK', max_length=20)),
                ('total_km', models.PositiveIntegerField(default=0)),
                ('km_since_last_retread', models.PositiveIntegerField(default=0)),
                ('max_km_life', models.PositiveIntegerField(default=50000)),
                ('retread_count', models.PositiveIntegerField(default=0)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='tenants.municipality')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('municipality', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VehicleTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('FRONT_LEFT', 'Dianteiro Esquerdo'), ('FRONT_RIGHT', 'Dianteiro Direito'), ('REAR_LEFT', 'Traseiro Esquerdo'), ('REAR_RIGHT', 'Traseiro Direito'), ('SPARE', 'Estepe')], max_length=32)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('installed_odometer', models.PositiveIntegerField(default=0)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_positions', to='maintenance.tire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tires', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['vehicle_id', 'position'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('vehicle', 'position'), name='unique_active_tire_position')],
            },
        ),
    ]
