# Generated by Django 5.1.13 on 2025-12-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inep_code', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('ESTADUAL', 'Estadual'), ('PARTICULAR', 'Particular'), ('FEDERAL', 'Federal'), ('OTHER', 'Outro')], default='MUNICIPAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='tenants.municipality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('municipality', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('social_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField()),
                ('cpf', models.CharField(db_index=True, max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('shift', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('FULLTIME', 'Integral'), ('EVENING', 'Noite')], default='MORNING', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('TRANSFERRED', 'Transferido'), ('INACTIVE', 'Inativo'), ('GRADUATED', 'Formado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.municipality')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.school')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('TRANSPORT', 'Transporte')], default='TRANSPORT', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('BLOCKED', 'Bloqueada'), ('EXPIRED', 'Expirada'), ('REPLACED', 'Substituída')], default='ACTIVE', max_length=20)),
                ('qr_payload', models.CharField(blank=True, max_length=255)),
                ('printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='tenants.municipality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransportRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_district', models.CharField(blank=True, max_length=100)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_district', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('FULLTIME', 'Integral'), ('EVENING', 'Noite')], default='MORNING', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transport_registrations', to='contracts.contract')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_registrations', to='tenants.municipality')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_registrations', to='students.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_registrations', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('municipality', 'cpf'), name='unique_active_student_cpf_per_municipality'),
        ),
        migrations.AddConstraint(
            model_name='studentcard',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'type'), name='unique_active_card_per_student_type'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcard',
            unique_together={('municipality', 'card_number')},
        ),
    ]
