# Generated by Django 5.1.5 on 2026-01-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0002_municipality_fuel_contract_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shift', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('FULLTIME', 'Integral'), ('EVENING', 'Noite')], default='MORNING', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='tenants.municipality')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='students.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('municipality', 'school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.classgroup'),
        ),
    ]
